apiVersion: v1
kind: Service
metadata:
  name: sil-triton
spec:
  selector:
    app: sil-triton
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 8001
      targetPort: 8001
